env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
settings:
  import/resolver: {
      node: {
        extensions: [".js", ".jsx", ".ts", ".tsx"]
      }
    }
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension: [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  import/extensions: 0
  react/jsx-props-no-spreading: 0
